
package com.campusmgmt.soa.foundation.messagedefinition;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.cmc_integration_kenyatta_wcf.KUPostLedgerRequest;
import org.datacontract.schemas._2004._07.cmc_integration_kenyatta_wcf.KUPostLedgerResponse;
import org.datacontract.schemas._2004._07.cmc_integration_kenyatta_wcf.VerifyStudentRequest;
import org.datacontract.schemas._2004._07.cmc_integration_kenyatta_wcf.VerifyStudentResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IKULedgerService", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")
@XmlSeeAlso({
    com.campusmgmt.soa.foundation.messagedefinition.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.cmc_campuslink_client_businessentities.ObjectFactory.class,
    org.datacontract.schemas._2004._07.cmc_campuslink_wcf_messages.ObjectFactory.class,
    org.datacontract.schemas._2004._07.cmc_integration_kenyatta_wcf.ObjectFactory.class
})
public interface IKULedgerService {


    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.cmc_integration_kenyatta_wcf.KUPostLedgerResponse
     * @throws IKULedgerServicePostLedgerServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "PostLedger", action = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd/IKULedgerService/PostLedger")
    @WebResult(name = "PostLedgerResult", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")
    @RequestWrapper(localName = "PostLedger", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", className = "com.campusmgmt.soa.foundation.messagedefinition.PostLedger")
    @ResponseWrapper(localName = "PostLedgerResponse", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", className = "com.campusmgmt.soa.foundation.messagedefinition.PostLedgerResponse")
    public KUPostLedgerResponse postLedger(
        @WebParam(name = "request", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")
        KUPostLedgerRequest request)
        throws IKULedgerServicePostLedgerServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.cmc_integration_kenyatta_wcf.VerifyStudentResponse
     * @throws IKULedgerServiceVerifyStudentDetailsServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "VerifyStudentDetails", action = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd/IKULedgerService/VerifyStudentDetails")
    @WebResult(name = "VerifyStudentDetailsResult", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")
    @RequestWrapper(localName = "VerifyStudentDetails", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", className = "com.campusmgmt.soa.foundation.messagedefinition.VerifyStudentDetails")
    @ResponseWrapper(localName = "VerifyStudentDetailsResponse", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", className = "com.campusmgmt.soa.foundation.messagedefinition.VerifyStudentDetailsResponse")
    public VerifyStudentResponse verifyStudentDetails(
        @WebParam(name = "request", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd")
        VerifyStudentRequest request)
        throws IKULedgerServiceVerifyStudentDetailsServiceFaultFaultFaultMessage
    ;

}
