
package com.campusmgmt.soa.foundation.messagedefinition;

import javax.xml.ws.WebFault;
import org.datacontract.schemas._2004._07.cmc_campuslink_wcf_messages.ServiceFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceFault", targetNamespace = "http://schemas.datacontract.org/2004/07/Cmc.CampusLink.Wcf.Messages.Common")
public class IKULedgerServicePostLedgerServiceFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IKULedgerServicePostLedgerServiceFaultFaultFaultMessage(String message, ServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IKULedgerServicePostLedgerServiceFaultFaultFaultMessage(String message, ServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.datacontract.schemas._2004._07.cmc_campuslink_wcf_messages.ServiceFault
     */
    public ServiceFault getFaultInfo() {
        return faultInfo;
    }

}
