
package com.campusmgmt.soa.foundation.messagedefinition;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KULedgerService", targetNamespace = "http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", wsdlLocation = "https://cvue-mapi.ku.ac.ke/UATPaymentGatewayService/KULedgerService.svc?wsdl")
public class KULedgerService
    extends Service
{

    private final static URL KULEDGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException KULEDGERSERVICE_EXCEPTION;
    private final static QName KULEDGERSERVICE_QNAME = new QName("http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", "KULedgerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cvue-mapi.ku.ac.ke/UATPaymentGatewayService/KULedgerService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KULEDGERSERVICE_WSDL_LOCATION = url;
        KULEDGERSERVICE_EXCEPTION = e;
    }

    public KULedgerService() {
        super(__getWsdlLocation(), KULEDGERSERVICE_QNAME);
    }

    public KULedgerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KULEDGERSERVICE_QNAME, features);
    }

    public KULedgerService(URL wsdlLocation) {
        super(wsdlLocation, KULEDGERSERVICE_QNAME);
    }

    public KULedgerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KULEDGERSERVICE_QNAME, features);
    }

    public KULedgerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KULedgerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IKULedgerService
     */
    @WebEndpoint(name = "BasicHttp")
    public IKULedgerService getBasicHttp() {
        return super.getPort(new QName("http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", "BasicHttp"), IKULedgerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IKULedgerService
     */
    @WebEndpoint(name = "BasicHttp")
    public IKULedgerService getBasicHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.campusmgmt.com/Soa/Foundation/MessageDefinition.xsd", "BasicHttp"), IKULedgerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KULEDGERSERVICE_EXCEPTION!= null) {
            throw KULEDGERSERVICE_EXCEPTION;
        }
        return KULEDGERSERVICE_WSDL_LOCATION;
    }

}
